from typing import List, Dict, Any
from backend.models.models import Destination, Place
from backend.database import SessionLocal, engine, Base

DESTINATIONS_DATA = [
    {
        "name": "Rishikesh",
        "state": "Uttarakhand",
        "country": "India",
        "latitude": 30.0869,
        "longitude": 78.2676,
        "theme_type": "mountain",
        "tagline": "Yoga Capital of the World & Gateway to the Himalayas",
        "description": "Nestled in the Himalayan foothills beside the sacred Ganges River, Rishikesh combines world-renowned spiritual tranquility with adrenaline-pumping white water rafting, cliff jumping, and scenic forest trails.",
        "hero_image": "https://images.unsplash.com/photo-1596707325608-25114704085b?w=1600&auto=format&fit=crop",
        "places": [
            {
                "name": "Ram Jhula",
                "category": "Spiritual",
                "description": "Historic suspension bridge across the holy Ganges River connecting Sivananda Ashram and Swargashram. Offers panoramic river views and lively riverside bazaars.",
                "latitude": 30.1235,
                "longitude": 78.3149,
                "rating": 4.6,
                "review_count": 18450,
                "open_time": "06:00",
                "close_time": "22:00",
                "duration_hours": 1.5,
                "entry_fee": 0.0,
                "is_hidden_gem": False,
                "popularity_score": 96.0,
                "image_url": "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&auto=format&fit=crop",
                "address": "Swarg Ashram, Rishikesh, Uttarakhand 249304",
                "best_time_to_visit": "Early morning or during sunset",
                "activity_type": "Sightseeing & Photography"
            },
            {
                "name": "The Beatles Ashram (Chaurasi Kutia)",
                "category": "Scenic Views",
                "description": "The legendary ashram of Maharishi Mahesh Yogi where The Beatles composed the White Album in 1968. Features psychedelic graffiti domes, meditation chambers, and Rajaji Tiger Reserve boundary.",
                "latitude": 30.1132,
                "longitude": 78.3188,
                "rating": 4.5,
                "review_count": 8920,
                "open_time": "09:00",
                "close_time": "16:30",
                "duration_hours": 2.0,
                "entry_fee": 150.0,
                "is_hidden_gem": False,
                "popularity_score": 91.0,
                "image_url": "https://images.unsplash.com/photo-1600100397608-f010f443b740?w=800&auto=format&fit=crop",
                "address": "Swargashram, Rishikesh, Uttarakhand 249304",
                "best_time_to_visit": "Morning hours",
                "activity_type": "Heritage & Photography"
            },
            {
                "name": "Neer Garh Waterfall",
                "category": "Hiking",
                "description": "Multi-tier turquoise natural waterfall hidden inside lush terraced forest hills. Involves a pleasant 20-minute trek and cool natural wading pools.",
                "latitude": 30.1472,
                "longitude": 78.3364,
                "rating": 4.5,
                "review_count": 9230,
                "open_time": "08:00",
                "close_time": "18:00",
                "duration_hours": 2.5,
                "entry_fee": 50.0,
                "is_hidden_gem": False,
                "popularity_score": 89.0,
                "image_url": "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=800&auto=format&fit=crop",
                "address": "Neergarh Waterfall Road, Rishikesh, Uttarakhand 249137",
                "best_time_to_visit": "Morning before crowds arrive",
                "activity_type": "Hiking & Swimming"
            },
            {
                "name": "Triveni Ghat & Maha Aarti",
                "category": "Spiritual",
                "description": "Sacred confluence of three holy rivers (Ganga, Yamuna, Saraswati). Famous for evening Maha Aarti with ceremonial oil lamps, bells, and spiritual chanting.",
                "latitude": 30.1037,
                "longitude": 78.2946,
                "rating": 4.7,
                "review_count": 21300,
                "open_time": "05:00",
                "close_time": "21:30",
                "duration_hours": 2.0,
                "entry_fee": 0.0,
                "is_hidden_gem": False,
                "popularity_score": 98.0,
                "image_url": "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop",
                "address": "Mayakund, Rishikesh, Uttarakhand 249201",
                "best_time_to_visit": "5:30 PM for the sunset Aarti",
                "activity_type": "Spiritual Ritual & Cultural Experience"
            },
            {
                "name": "Shivpuri White Water Rafting",
                "category": "Water Activities",
                "description": "Exhilarating 16-km grade III/IV river rafting stretch featuring famous rapids like Roller Coaster, Golf Course, and Club House, ending with cliff jumping.",
                "latitude": 30.1420,
                "longitude": 78.3889,
                "rating": 4.8,
                "review_count": 14200,
                "open_time": "07:30",
                "close_time": "17:00",
                "duration_hours": 3.5,
                "entry_fee": 1000.0,
                "is_hidden_gem": False,
                "popularity_score": 97.0,
                "image_url": "https://images.unsplash.com/photo-1530866495561-507c9faab2ed?w=800&auto=format&fit=crop",
                "address": "Shivpuri Rafting Camp Area, Badrinath Rd, Uttarakhand 249192",
                "best_time_to_visit": "September to June (Clear water)",
                "activity_type": "White Water Rafting & Cliff Jumping"
            },
            {
                "name": "Patna Waterfall & Limestone Caves",
                "category": "Hidden Gems",
                "description": "Quiet, untouched cascade surrounded by deep limestone caves and wild Himalayan flora. A peaceful escape 5 km ahead of Lakshman Jhula with virtually zero commercial crowds.",
                "latitude": 30.1345,
                "longitude": 78.3610,
                "rating": 4.6,
                "review_count": 1650,
                "open_time": "08:00",
                "close_time": "17:30",
                "duration_hours": 2.0,
                "entry_fee": 0.0,
                "is_hidden_gem": True,
                "popularity_score": 78.0,
                "image_url": "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop",
                "address": "Patna Village, Neelkanth Temple Road, Rishikesh",
                "best_time_to_visit": "Morning 9:00 AM",
                "activity_type": "Cave Trek & Nature Dip"
            },
            {
                "name": "Vashistha Cave (Gufa)",
                "category": "Hidden Gems",
                "description": "Ancient meditative cave where Sage Vashistha meditated beside the roaring Ganga. Radiates profound silence and cool subterranean stillness right off a private white sand riverbank.",
                "latitude": 30.1982,
                "longitude": 78.4312,
                "rating": 4.8,
                "review_count": 2100,
                "open_time": "09:00",
                "close_time": "17:00",
                "duration_hours": 1.5,
                "entry_fee": 0.0,
                "is_hidden_gem": True,
                "popularity_score": 79.0,
                "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop",
                "address": "Badrinath Road, Shivpuri Range, Uttarakhand 249192",
                "best_time_to_visit": "Early afternoon for deep meditation",
                "activity_type": "Meditation & River Beach Walk"
            },
            {
                "name": "Kunjapuri Temple Sunrise Peak",
                "category": "Scenic Views",
                "description": "Perched at 1,665m altitude, offers breathtaking 360-degree vistas of Himalayan snow peaks (including Chaukhamba and Swargarohini) and the glistening Ganges basin.",
                "latitude": 30.1878,
                "longitude": 78.2912,
                "rating": 4.7,
                "review_count": 5890,
                "open_time": "05:00",
                "close_time": "19:00",
                "duration_hours": 3.0,
                "entry_fee": 0.0,
                "is_hidden_gem": False,
                "popularity_score": 90.0,
                "image_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop",
                "address": "Hindolakhal Rd, Tehri Garhwal, Uttarakhand 249175",
                "best_time_to_visit": "5:00 AM for sunrise viewpoint",
                "activity_type": "Sunrise Trek & Panoramic Photography"
            },
            {
                "name": "Little Buddha Cafe & German Bakery",
                "category": "Food",
                "description": "Iconic riverside treehouse-style cafe serving artisanal wood-fired pizzas, herbal teas, Israeli platters, and organic smoothies overlooking the Ganges.",
                "latitude": 30.1260,
                "longitude": 78.3245,
                "rating": 4.4,
                "review_count": 6700,
                "open_time": "08:00",
                "close_time": "22:30",
                "duration_hours": 1.5,
                "entry_fee": 0.0,
                "is_hidden_gem": False,
                "popularity_score": 88.0,
                "image_url": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop",
                "address": "Laxman Jhula Rd, Tapovan, Rishikesh, Uttarakhand 249192",
                "best_time_to_visit": "Sunset to twilight",
                "activity_type": "Dining & Riverside Relaxation"
            },
            {
                "name": "Parmarth Niketan Ganga Ghat",
                "category": "Spiritual",
                "description": "Largest ashram in Rishikesh with sprawling floral gardens, iconic Lord Shiva statue rising from the river, and daily universal prayer gatherings.",
                "latitude": 30.1190,
                "longitude": 78.3120,
                "rating": 4.7,
                "review_count": 12400,
                "open_time": "06:00",
                "close_time": "21:00",
                "duration_hours": 1.5,
                "entry_fee": 0.0,
                "is_hidden_gem": False,
                "popularity_score": 94.0,
                "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop",
                "address": "Main Market Rd, Ram Jhula, Swarg Ashram, Rishikesh",
                "best_time_to_visit": "Late afternoon",
                "activity_type": "Yoga, Meditation & Aarti"
            }
        ]
    },
    {
        "name": "Goa",
        "state": "Goa",
        "country": "India",
        "latitude": 15.2993,
        "longitude": 74.1240,
        "theme_type": "beach",
        "tagline": "Golden Sands, Portuguese Heritage & Tropical Bliss",
        "description": "World-famed coastal paradise boasting sun-kissed beaches, Portuguese colonial architecture, vibrant night markets, and thrilling water sports.",
        "hero_image": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1600&auto=format&fit=crop",
        "places": [
            {
                "name": "Palolem Beach",
                "category": "Water Activities",
                "description": "Crescent-shaped white sand bay lined with coconut palms, colorful beach shacks, and calm shallow waters ideal for kayaking and dolphin cruises.",
                "latitude": 15.0100,
                "longitude": 74.0232,
                "rating": 4.6,
                "review_count": 16800,
                "open_time": "06:00",
                "close_time": "23:00",
                "duration_hours": 3.0,
                "entry_fee": 0.0,
                "is_hidden_gem": False,
                "popularity_score": 95.0,
                "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop",
                "address": "Canacona, South Goa, 403702",
                "best_time_to_visit": "Late afternoon to sunset",
                "activity_type": "Kayaking & Beach Lounging"
            },
            {
                "name": "Dudhsagar Waterfalls",
                "category": "Adventure",
                "description": "Majestic four-tiered waterfall cascading 310 meters down the Western Ghats like a sea of milk, accessible by thrilling 4x4 jungle jeep safari.",
                "latitude": 15.3144,
                "longitude": 74.3143,
                "rating": 4.6,
                "review_count": 13900,
                "open_time": "08:00",
                "close_time": "16:00",
                "duration_hours": 4.0,
                "entry_fee": 500.0,
                "is_hidden_gem": False,
                "popularity_score": 93.0,
                "image_url": "https://images.unsplash.com/photo-1582650625119-3a31f841836d?w=800&auto=format&fit=crop",
                "address": "Sonaulim, Goa 403410",
                "best_time_to_visit": "Morning 8:00 AM",
                "activity_type": "Jeep Safari & Trekking"
            },
            {
                "name": "Fontainhas Latin Quarter",
                "category": "Scenic Views",
                "description": "Charming UNESCO heritage quarter in Panaji filled with vivid pastel Portuguese villas, wrought iron balconies, and heritage bakeries.",
                "latitude": 15.4989,
                "longitude": 73.8310,
                "rating": 4.5,
                "review_count": 9100,
                "open_time": "08:00",
                "close_time": "20:00",
                "duration_hours": 2.0,
                "entry_fee": 0.0,
                "is_hidden_gem": False,
                "popularity_score": 90.0,
                "image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop",
                "address": "Panaji, Goa 403001",
                "best_time_to_visit": "Late morning for photography",
                "activity_type": "Heritage Walking Tour"
            },
            {
                "name": "Butterfly Beach & Hidden Cove",
                "category": "Hidden Gems",
                "description": "Secluded secret amphitheater beach accessible only via boat from Agonda or a steep jungle trek. Home to dolphins, sea anemones, and golden sands.",
                "latitude": 15.0160,
                "longitude": 74.0080,
                "rating": 4.7,
                "review_count": 2400,
                "open_time": "07:00",
                "close_time": "18:30",
                "duration_hours": 2.5,
                "entry_fee": 0.0,
                "is_hidden_gem": True,
                "popularity_score": 82.0,
                "image_url": "https://images.unsplash.com/photo-1510414842594-a61752afb394?w=800&auto=format&fit=crop",
                "address": "Near Palolem, Canacona, South Goa",
                "best_time_to_visit": "Morning before high tide",
                "activity_type": "Dolphin Spotting & Private Swimming"
            }
        ]
    },
    {
        "name": "Manali",
        "state": "Himachal Pradesh",
        "country": "India",
        "latitude": 32.2396,
        "longitude": 77.1887,
        "theme_type": "mountain",
        "tagline": "Valley of Gods, Snow Peaks & Pine Forests",
        "description": "High-altitude Himalayan resort town known for cool alpine climate, cedar forests, snow valleys, and rustic wooden temples.",
        "hero_image": "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1600&auto=format&fit=crop",
        "places": [
            {
                "name": "Hadimba Temple",
                "category": "Spiritual",
                "description": "Unique 16th-century four-tier pagoda wooden temple dedicated to Hidimbi Devi, set amidst towering giant deodar cedar forests.",
                "latitude": 32.2483,
                "longitude": 77.1692,
                "rating": 4.6,
                "review_count": 22100,
                "open_time": "08:00",
                "close_time": "18:00",
                "duration_hours": 1.5,
                "entry_fee": 0.0,
                "is_hidden_gem": False,
                "popularity_score": 96.0,
                "image_url": "https://images.unsplash.com/photo-1605649487212-47bdab064df8?w=800&auto=format&fit=crop",
                "address": "Hadimba Temple Rd, Old Manali, 175131",
                "best_time_to_visit": "Morning 9:00 AM",
                "activity_type": "Cedar Forest Walk & Cultural Visit"
            },
            {
                "name": "Solang Valley Adventures",
                "category": "Adventure",
                "description": "Year-round action hub offering paragliding, zorbing, ATV quad biking, and winter snow skiing against dramatic Himalayan ridges.",
                "latitude": 32.3166,
                "longitude": 77.1575,
                "rating": 4.5,
                "review_count": 19400,
                "open_time": "09:00",
                "close_time": "18:00",
                "duration_hours": 3.5,
                "entry_fee": 0.0,
                "is_hidden_gem": False,
                "popularity_score": 95.0,
                "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop",
                "address": "Solang Valley, Burwa, Himachal Pradesh 175131",
                "best_time_to_visit": "Morning hours",
                "activity_type": "Paragliding & Snow Activities"
            },
            {
                "name": "Jogini Waterfalls & Vashisht Trek",
                "category": "Hidden Gems",
                "description": "Scenic 3-km pine forest trail leading to a roaring cascade dropping into the Beas River valley. Pass apple orchards and ancient sulfur hot springs.",
                "latitude": 32.2680,
                "longitude": 77.1950,
                "rating": 4.7,
                "review_count": 4800,
                "open_time": "07:00",
                "close_time": "18:00",
                "duration_hours": 2.5,
                "entry_fee": 0.0,
                "is_hidden_gem": True,
                "popularity_score": 85.0,
                "image_url": "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop",
                "address": "Vashisht Village, Manali, Himachal Pradesh 175103",
                "best_time_to_visit": "10:00 AM sunny morning",
                "activity_type": "Hiking & Forest Trail"
            }
        ]
    },
    {
        "name": "Jaipur",
        "state": "Rajasthan",
        "country": "India",
        "latitude": 26.9124,
        "longitude": 75.7873,
        "theme_type": "desert",
        "tagline": "The Royal Pink City of Palaces and Forts",
        "description": "Historic Rajasthani capital famed for majestic hilltop fortresses, pink terracotta sandstone architecture, astronomy observatories, and royal bazaars.",
        "hero_image": "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1600&auto=format&fit=crop",
        "places": [
            {
                "name": "Amber Fort & Palace",
                "category": "Scenic Views",
                "description": "Magnificent hilltop palace complex built of yellow and pink sandstone with Sheesh Mahal (Mirror Palace) and panoramic Maota Lake reflections.",
                "latitude": 26.9855,
                "longitude": 75.8513,
                "rating": 4.7,
                "review_count": 34000,
                "open_time": "08:00",
                "close_time": "17:30",
                "duration_hours": 3.0,
                "entry_fee": 100.0,
                "is_hidden_gem": False,
                "popularity_score": 98.0,
                "image_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop",
                "address": "Devisinghpura, Amer, Jaipur, Rajasthan 302001",
                "best_time_to_visit": "Early morning to avoid midday sun",
                "activity_type": "Historical Architecture Tour"
            },
            {
                "name": "Hawa Mahal (Palace of Winds)",
                "category": "Scenic Views",
                "description": "Iconic five-story facade featuring 953 intricately carved honeycomb jharokha windows allowing royal women to observe street festivities unobserved.",
                "latitude": 26.9239,
                "longitude": 75.8267,
                "rating": 4.5,
                "review_count": 28900,
                "open_time": "09:00",
                "close_time": "17:00",
                "duration_hours": 1.5,
                "entry_fee": 50.0,
                "is_hidden_gem": False,
                "popularity_score": 96.0,
                "image_url": "https://images.unsplash.com/photo-1609873963590-b184f479e0a2?w=800&auto=format&fit=crop",
                "address": "Hawa Mahal Rd, Badi Choupad, J.D.A. Market, Jaipur",
                "best_time_to_visit": "Morning light strikes the facade",
                "activity_type": "Architecture & Rooftop Cafe Views"
            },
            {
                "name": "Panna Meena Ka Kund Stepwell",
                "category": "Hidden Gems",
                "description": "Stunning 16th-century symmetrical geometric stepwell tucked beside Amber town. Remarkable interlocking zigzag staircases creating hypnotic optical patterns.",
                "latitude": 26.9940,
                "longitude": 75.8560,
                "rating": 4.6,
                "review_count": 3200,
                "open_time": "07:00",
                "close_time": "18:00",
                "duration_hours": 1.0,
                "entry_fee": 0.0,
                "is_hidden_gem": True,
                "popularity_score": 84.0,
                "image_url": "https://images.unsplash.com/photo-1585123388867-3bfe6dd4bdbf?w=800&auto=format&fit=crop",
                "address": "Near Anokhi Museum, Amer, Jaipur 302028",
                "best_time_to_visit": "Early morning 8:00 AM",
                "activity_type": "Heritage Geometry & Photography"
            }
        ]
    },
    {
        "name": "Meghalaya",
        "state": "Meghalaya",
        "country": "India",
        "latitude": 25.5788,
        "longitude": 91.8933,
        "theme_type": "forest",
        "tagline": "Abode of Clouds, Living Root Bridges & Crystal Waters",
        "description": "Lush northeastern wonderland with mist-laden hills, the cleanest village in Asia, subterranean limestone caves, and centuries-old living tree root bridges.",
        "hero_image": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1600&auto=format&fit=crop",
        "places": [
            {
                "name": "Double Decker Living Root Bridge",
                "category": "Hiking",
                "description": "Incredible bio-engineering marvel crafted over generations by Khasi tribes weaving Ficus elastica aerial roots across torrential rivers.",
                "latitude": 25.2500,
                "longitude": 91.6700,
                "rating": 4.8,
                "review_count": 7800,
                "open_time": "06:00",
                "close_time": "17:00",
                "duration_hours": 4.5,
                "entry_fee": 50.0,
                "is_hidden_gem": False,
                "popularity_score": 97.0,
                "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop",
                "address": "Nongriat, Cherrapunji (Sohra), Meghalaya 793108",
                "best_time_to_visit": "Morning 7:00 AM to start descent",
                "activity_type": "3000-Step Rainforest Trek"
            },
            {
                "name": "Dawki Umngot River Boat Ride",
                "category": "Water Activities",
                "description": "World-famous glass-clear river where wooden boats appear suspended in thin air above colorful river pebbles right along the India-Bangladesh border.",
                "latitude": 25.1833,
                "longitude": 92.0167,
                "rating": 4.7,
                "review_count": 9100,
                "open_time": "08:00",
                "close_time": "17:00",
                "duration_hours": 2.5,
                "entry_fee": 800.0,
                "is_hidden_gem": False,
                "popularity_score": 94.0,
                "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop",
                "address": "Umngot River, Dawki, West Jaintia Hills, Meghalaya",
                "best_time_to_visit": "November to April for crystal waters",
                "activity_type": "Boating & Cliff Jumping"
            },
            {
                "name": "Krem Puri Cave System",
                "category": "Hidden Gems",
                "description": "The world's longest sandstone cave system (over 24 km long) harboring dinosaur fossils, subterranean crystal pools, and massive calcite halls.",
                "latitude": 25.3200,
                "longitude": 91.5600,
                "rating": 4.8,
                "review_count": 920,
                "open_time": "08:30",
                "close_time": "16:00",
                "duration_hours": 3.0,
                "entry_fee": 150.0,
                "is_hidden_gem": True,
                "popularity_score": 80.0,
                "image_url": "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=800&auto=format&fit=crop",
                "address": "Mawsynram, East Khasi Hills, Meghalaya",
                "best_time_to_visit": "Morning with certified guide",
                "activity_type": "Caving & Geological Expedition"
            }
        ]
    }
]

def seed_database():
    """Initializes and seeds database tables if empty."""
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        if db.query(Destination).count() == 0:
            print("Seeding Travel Explorer destinations and places...")
            for dest_data in DESTINATIONS_DATA:
                places_data = dest_data.pop("places")
                dest = Destination(**dest_data)
                db.add(dest)
                db.flush() # generate dest.id

                for p_data in places_data:
                    place = Place(destination_id=dest.id, **p_data)
                    db.add(place)
            db.commit()
            print("Database seeded successfully with verified destinations & authentic attractions!")
        else:
            print("Database already contains destination data.")
    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    seed_database()
